// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pquwoxwnqfgedkdeakev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxdXdveHducWZnZWRrZGVha2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzcwNzQsImV4cCI6MjA2NjE1MzA3NH0.g3OkYj_OE4oFWiLADfmqA01A94fFdrQnT-LY8QvD4bU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);